### ISSUE TITLE
Hey Samurai do you can help me?

### ISSUE THREAD

**Issue by luscff99** [Samurai9954/Infinity-Square-AI-Portal#1]
the subject is different from this topic here because I still don't know how to use Github very well

So, my metasploit is showing this screen whenever I try to open it, it is not an error because it opens quietly but I wanted to know what it was, it didn't appear before.

![Screenshot_20200912-003601.png](https://user-images.githubusercontent.com/70997343/92986394-ce30e400-f490-11ea-81e8-bdccc0c6e362.png)

**Comment by Samurai9954** [comment]
umm.... what are you trying to do? and why did you make a issue on my repo? im closing this and you can talk to me through discord my id is @MICROSOFT TOAST
